import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 28px;
        }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to hunting coder</h1>
        <Image
          className={styles.myImg}
          src="/homeimg.jpg"
          alt=""
          width={237}
          height={158}
        />
        <p>A blog by hunting coder by hunting coder</p>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to Learn Javascript in 2022</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora
              porro maiores similique aperiam dicta minus delectus dolorem quae
              sit fugiat!
            </p>
          </div>
          <div className="blogItem">
            <h3>How to Learn Javascript in 2022</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora
              porro maiores similique aperiam dicta minus delectus dolorem quae
              sit fugiat!
            </p>
          </div>
          <div className="blogItem">
            <h3>How to Learn Javascript in 2022</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora
              porro maiores similique aperiam dicta minus delectus dolorem quae
              sit fugiat!
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
